version: '3.4'

services:
  sodachat:
    image: sodachat
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 8667:8667
    volumes: 
      - ./sources/db:/app/sources/db
      - ./sources/fonctions:/app/sources/fonctions
      - ./sources/static:/app/sources/static
      - ./sources/templates:/app/sources/templates
